"""empty message

Revision ID: 9f0e9c242c33
Revises: 
Create Date: 2018-04-25 11:31:55.331154

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9f0e9c242c33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('species', sa.String(length=100), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('description', sa.String(length=1000), nullable=True),
                    sa.Column('purchase_cost', sa.Float(), nullable=True),
                    sa.Column('purchase_date', sa.Date(), nullable=True),
                    sa.Column('planted_date', sa.Date(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tree')
    # ### end Alembic commands ###
